<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sc_dsacharmanager"
 *
 * Auto generated by Extension Builder 2016-12-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'DSA Character Manager',
	'description' => 'Management for DSA Characters',
	'category' => 'plugin',
	'author' => 'Sebastian Christoph',
	'author_email' => 'sxbxstxxn@googlemail.com',
	'state' => 'experimental',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);